apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-price-prediction-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flight-price-prediction
  template:
    metadata:
      labels:
        app: flight-price-prediction
    spec:
      containers:
      - name: flight-price-prediction-container
        image: varghesetito/flight-price-prediction
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: FLASK_APP
          value: "production"
